### ISSUE TITLE
Auth MVP Completed

### ISSUE THREAD

**Issue by khaliqzohaib92** [khaliqzohaib92/FriendsFlix#4]
Following feature has been completed in auth MVP.
- User sign in, sign up and sign out
- Demo sign in
- User can manage different profiles under one account
- Error handling on forms
- Styling of splash screen, sign in, sign up, profile listing, profile add/edit and profile management.

[LIVE LINK](https://friendsflix.herokuapp.com/#/)

**Comment by rlim92** [comment]
Hey Zohaib! Really great work so far. Small changes: 

- [ ] the blurb at the bottom of each signup/signin page should be switched ("New to Netflix?" should link to the sign up page)
- [ ] there seems to only be a sign in button on the real website. Consider having just a sign in button and then on the form u can have a link to the sign up.
